---
language: python
services: docker

env:
  global:
    - ROLE_NAME: openvpn
  matrix:
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

before_install:
  # Upgrade Docker to work with docker-py.
  - curl https://gist.githubusercontent.com/geerlingguy/ce883ad4aec6a5f1187ef93bd338511e/raw/36612d28981d92863f839c5aefe5b7dd7193d6c6/travis-ci-docker-upgrade.sh | sudo bash

install:
  # Install test dependencies.
  - pip install molecule[docker] yamllint ansible-lint docker flake8 testinfra

script:
  # Run tests.
  - molecule test

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    if: branch = master
  email:
    on_success: change
    on_failure: change
