---
- name: Generate private key for {{ openvpn_client.name }}
  openssl_privatekey:
    path: "{{ openvpn_ca_path }}/{{ openvpn_client.name }}.key"
    passphrase: "{{ openvpn_client.keypass|default(omit) }}"
    cipher: "{{ 'auto' if openvpn_client.keypass is defined else omit }}"

- name: Generate CSR for {{ openvpn_client.name }}
  openssl_csr:
    path: "{{ openvpn_ca_path }}/{{ openvpn_client.name }}.csr"
    privatekey_path: "{{ openvpn_ca_path }}/{{ openvpn_client.name }}.key"
    privatekey_passphrase: "{{ openvpn_client.keypass|default(omit) }}"
    common_name: "{{ openvpn_client.name }}"

- name: Sign {{ openvpn_client.name }} with CA
  openssl_certificate:
    path: "{{ openvpn_ca_path }}/{{ openvpn_client.name }}.crt"
    csr_path: "{{ openvpn_ca_path }}/{{ openvpn_client.name }}.csr"
    ownca_path: "{{ openvpn_ca_crt }}"
    ownca_privatekey_path: "{{ openvpn_ca_key }}"
    ownca_privatekey_passphrase: "{{ openvpn_ca_pass }}"
    provider: ownca
